### ISSUE TITLE
在网关处实现用户身份校验

### ISSUE THREAD

**Issue by QubitPi** [paion-data/immutable-infrastructure-as-a-service#47]
> [!IMPORTANT]
>
> 本次工作是进行软件部署之前，所有代码编写工作的“临门一脚”，而且涉及用户数据安全，非常重要！

![auth](https://github.com/paion-data/immutable-infrastructure-as-a-service/assets/16126939/7a773d5f-1cd5-498d-9817-83f979685f6c)

可以看到，访问 astraios, minerval，机器学习的网络请求全部是 HTTP，这么做的好处是大大简化了架构中用户身份校验（Authentication）的逻辑。身份校验从 Spring web 服务剥离之后，将放在网关处解决。那么本次工作的目标就是在我们的 Kong API 网关实现用户身份校验逻辑

## 工作目标

**在我们的 Kong API 网关实现用户身份校验逻辑，使得只有登录了前端的合法用户才能通过网关访问后台 web 服务**

## 技术设计

> [!TIP]
>
> @A-Little-Excited 这不是你一人在设计，这牵扯到运维如何支持你的逻辑（ @qing-wq ），前端如何发送请求（ @ziqingbanmianzhuang ），你需要和对方对话商讨，不是闭门造车，务必多沟通交流。如果遇到任何问题或者疑问，务必及时告知 @QubitPi @qing-wq @ziqingbanmianzhuang 一起讨论解决方案

> [!IMPORTANT]
>
> 技术设计的 Deadline 是 **2024 年 5 月 20 号**

开始设计之前 @QubitPi 对 @A-Little-Excited @qing-wq 做一个 OAuth2 培训

完成本次工作须要 @A-Little-Excited 对如下技术有深刻的学习和理解：

- [OAuth 2](https://oauth.net/2/) (Authorization) & [**OIDC**](https://openid.net/developers/how-connect-works/) (**Authentication**)
- [Kong API Gateway](https://docs.konghq.com/gateway/latest/)
- [Logto](https://docs.logto.io/)

前端的用户登录是用 [Logto](https://docs.logto.io/) 实现的，用户登录进来后，Logto 会代理微信，下发一个 access token，合法的用户会在所有前端请求的 header 中放入这个 access token，**Kong API 网关须要校验**

1. **请求中是否带了 access token** (和 @ziqingbanmianzhuang 确认存放在哪个 header 里面)
3. **向 Logto 验证 access token 是否合法**

> [!IMPORTANT]
>
> 我们定义**同时**满足如下条件的 access token 为合法 token:
>
> 1. 该 token 是一个合法的 [JWT token](https://jwt.io/)
> 2. token 对应的用户身份（OIDC ID （即 [sub](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.2)））和 Logto 方的数据库用户记录完全 match

## 实现

> [!IMPORTANT]
>
> 实现的 Deadline 是 **2024 年 5 月 27 号**

根据 @A-Little-Excited 的设计确定具体实现。**由 @A-Little-Excited 负责编写实现计划**

实现计划要求：

- 细化、细化、细化：

  - 如何在 Kong API 网关实现埋点？用 OAuth2 插件，还是其他方法？
  - 用哪个第三方库校验 JWT 的格式正确性？
  - 前端传过来的 OIDC ID 将调用 logto 的哪个资源进行身份验证？
  - 一个 PR 就够了，还是几个 PR？如果是多个 PR，每个 Deadline 是什么时候？
  - 代码写在哪里？
  - 必要时候需要有[业务流程图](https://plantuml.com/sequence-diagram)
  - 等等

- 技术实现以书面文字的形式，写在该 issue 的评论区即可，务必**详细**

**Comment by A-Little-Excited** [comment]
根据 @QubitPi 提供的与 Logto 开发人员在 Discord 上的对话记录中可以看出，Logto 官方并没有直接对外提供一个 token endpoint 这么一个自检端口，用来给我们发送请求校验 token 的合法性，因此我们不能遵循一开始想要使用 [OAuth 2.0 Introspection 插件](https://docs.konghq.com/hub/kong-inc/oauth2-introspection/)的想法，转而改为使用 [Kong 官方的 JWT 插件](https://docs.konghq.com/hub/kong-inc/jwt/)。该插件可以满足我们进行简化版的 token 校验任务。
该插件的使用需要我们配置好校验 token 所需的密钥( 此处为 Logto 官方提供的 JWKS URI 获取到的公钥 )和指定的算法( 此处默认为 ES384 )来进行校验，具体做法如下：

- 创建一个 consumer 
- 创建归属上述 consumer 的一个 JWT 凭证，并通过 algorithm 指定算法，通过 rsa_public_key 指定公钥( 由于此处是使用 ES384，因此是使用该字段设置公钥 )，后续前端发送给后端的请求都会使用该 JWT 凭证中指定的算法和公钥来进行 token 校验
- 在该插件的配置信息中，使用 config.header_names 来指定从请求的哪个 header 中获取 token

**Comment by QubitPi** [comment]
@A-Little-Excited Good 👍 

- [docker](https://github.com/Kong/docker-kong)
- 使用开发环境的 logoto 获取密钥对
- 本地启动 docker 测试上面的方案
- 如果通过，直接和 @qing-wq 对接实施
